### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by vzxx77x** [andresoviedo/google-drive-ftp-adapter-online#5]
Please i will be thankful if you can give me the instruction from the beginning to the end
Start with what os i must use in the server (centos or ubuntu)
And please tell me all the command to put in the servers because i don't have the experience in this things
Thank you

**Comment by andresoviedo** [comment]
Sorry. I am too busy to help right now.
Regards

**Comment by vzxx77x** [comment]
:(
